//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public string id_article { get; set; }
        public string id_category { get; set; }
        public string title_article { get; set; }
        public string alias_article { get; set; }
        public string id_user { get; set; }
        public string description_article { get; set; }
        public Nullable<System.DateTime> time_pulish_article { get; set; }
        public Nullable<System.DateTime> time_write { get; set; }
        public string state_article { get; set; }
        public byte[] img_article { get; set; }
        public string linkvideo_article { get; set; }
    
        public virtual CategoryArticle CategoryArticle { get; set; }
        public virtual InfoAccount InfoAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
