//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string id_car { get; set; }
        public string overview_car { get; set; }
        public string length_car { get; set; }
        public string wheels_car { get; set; }
        public string tireparameters_car { get; set; }
        public string weight_car { get; set; }
        public string capacity_car { get; set; }
        public string horsepower_car { get; set; }
        public string gear_car { get; set; }
        public string torque_car { get; set; }
        public string drivetype_car { get; set; }
        public string frontbrakesystem_car { get; set; }
        public string rearbrakesystem_car { get; set; }
        public string maximumspeed_car { get; set; }
        public string accelerationtime_car { get; set; }
        public string capacitytank_car { get; set; }
        public string numberseat_car { get; set; }
        public string seat_car { get; set; }
        public string airconditioner_car { get; set; }
        public string sunroof_car { get; set; }
        public Nullable<int> charge_car { get; set; }
        public string img_car { get; set; }
        public string id_version { get; set; }
    
        public virtual Version Version { get; set; }

        public string automakerId { get; set; }
        public string modelId { get; set; }
        public string versionId { get; set; }

        public string automakerId1 { get; set; }
        public string modelId1 { get; set; }
        public string versionId1 { get; set; }

        public string automakerId2 { get; set; }
        public string modelId2 { get; set; }
        public string versionId2 { get; set; }

        public string automakerId3 { get; set; }
        public string modelId3 { get; set; }
        public string versionId3 { get; set; }
    }
}
