//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string id_contact { get; set; }
        public string name_contact { get; set; }
        public string email_contact { get; set; }
        public string state_contact { get; set; }
        public Nullable<System.DateTime> date_contact { get; set; }
        public string subject_contact { get; set; }
    }
}
