//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Permission
    {
        public string id_typeuser { get; set; }
        public string id_permission { get; set; }
        public string note_permission { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
