//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_()
        {
            this.Articles = new HashSet<Article>();
            this.Comments = new HashSet<Comment>();
        }
    
        public string id_user { get; set; }
        public string name_user { get; set; }
        public string password_user { get; set; }
        public string id_typeuser { get; set; }
        public string lname_user { get; set; }
        public string fname_user { get; set; }
        public string email_user { get; set; }
        public string avt_user { get; set; }
        public string block_state_user { get; set; }
        public Nullable<System.DateTime> registerdate_user { get; set; }
        public Nullable<System.DateTime> lastvisitdate_user { get; set; }
        public string phone_user { get; set; }
        public string sex_user { get; set; }
        public Nullable<System.DateTime> birthday_user { get; set; }
        public string address_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
