//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComparison.Areas.Admin.Models
{
    using System;
    
    public partial class XemTenXe_Result1
    {
        public string name_automaker { get; set; }
        public string name_model { get; set; }
        public string name_version { get; set; }
        public string id_car { get; set; }
    }
}
